// <auto-generated />
using System;
using ChooseOne.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChooseOne.Database.Migrations
{
    [DbContext(typeof(ChooseOneContext))]
    [Migration("20230127113611_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("ChooseOne.Core.Domain.Entities.Customization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id");

                    b.Property<string>("BackGroundColor")
                        .HasColumnName("BackGroundColor");

                    b.Property<int>("ChooseComponent")
                        .HasColumnName("ChooseComponent");

                    b.Property<string>("Content")
                        .HasColumnName("Content");

                    b.Property<string>("CornerRadius")
                        .HasColumnName("CornerRadius");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnName("CreationDate");

                    b.Property<string>("ForeGroundColor")
                        .HasColumnName("ForeGroundColor");

                    b.Property<string>("MaxValue")
                        .HasColumnName("MaxValue");

                    b.Property<string>("MinValue")
                        .HasColumnName("MinValue");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Customizations");
                });
#pragma warning restore 612, 618
        }
    }
}
